"batch_size": 512
"device": "cpu"
"snr": 20.0
"seed": 42
"dataset": 'cifar10'
"antennas_transmitter": 4
"antennas_receiver": 4
"base_station_model": "vit_tiny_patch16_224" #:torch.Size([192, 42500])
"agents_models": 
    - vit_small_patch16_224
    - vit_small_patch32_224
    - vit_base_patch16_224
    - vit_base_patch32_clip_224
    - rexnet_100
    - mobilenetv3_small_075
    - mobilenetv3_large_100
    - mobilenetv3_small_100
    - efficientvit_m5.r224_in1k
    - levit_128s.fb_dist_in1k
"channel_usage": 1
"strategy": "FK"