defaults:
  - _self_

seed: 42
device: cpu
simulation: example

datamodule:
  dataset: cifar10
  train_subset_ratio: 1.0
  batch_size: 512

metrics:
  train_acc: false
  val_acc: false

communication:
  snr: 20.0
  square: true
  channel_usage: 4
  antennas_receiver: 4
  antennas_transmitter: 4
  
base_station:
  model: vit_tiny_patch16_224
  lr: 1e-1
  px_cost: 1.0
  strategy: First-K
  iterations: 30
  channel_aware: true

agents:
  models:
    - vit_small_patch16_224
    - vit_small_patch32_224
    - vit_base_patch16_224
    - vit_base_patch32_clip_224
    - rexnet_100
    - mobilenetv3_small_075
    - mobilenetv3_large_100
    - mobilenetv3_small_100
    - efficientvit_m5.r224_in1k
    - levit_128s.fb_dist_in1k

wandb:
  project: multi_agent_semantic_alignment__baseline_model
